### ISSUE TITLE
Consider adding to the setup passage of the readme

### ISSUE THREAD

**Issue by matanox** [habeanf/yap#4]
Perhaps consider explicitly asking to change directory to subdirectory `yap` ― or whatever other name the person cloning the repo insists on using with some fancy unnecessary git option ― before issuing `go get .`. It seems to be required for building the project after a clone, yet a golang newb won't necessarily guess, as the overall setup can be a little unearthly for a non-golanger at first glance.

Alternatively, a minor [imports style refactor suggested on SO](https://stackoverflow.com/q/47187280/1509695) might later follow, in some future tour of the code.

**Comment by habeanf** [comment]
You are correct, I forgot to add the `cd` into the cloned directory. I don't like the ``import "github.com/..."`` style because it binds the project to a specific URL. What if I want to move it to another provider like bitbucket/gitlab? How about serving from an organization's intranet without internet access?
Fixed in commit 9cfef68
