### ISSUE TITLE
Empty values on missing fields

### ISSUE THREAD

**Issue by DanielJuravski** [habeanf/yap#7]
1.
 I noticed that there are some inconsistency in the morphology file.
It contains several fields like word, lemma, pos, morphology etc. for every word in a sentence.

 Following your README, if some field is not available - the value will be '_'.
But  in practice, those unavailable fields are just missing, skipping to the next field.

Do you plan to fix that issue?

2. 
Another question is, on some morphological field, I get the following result:
> התקשרו	התקשר	VB	VB	gen=F|gen=M|num=P|per=3|tense=PAST	8	relcomp	_	_

What is the meaning of the double appearance of 'gen' ?

**Comment by habeanf** [comment]
You should know that this repository is no longer maintained. The new repository is at https://github.com/OnlpLab/yap and is managed by my advisor Reut Tsarfaty and her students at the Open University NLP Lab ( https://www.openu.ac.il/en/personalsites/ReutTsarfaty.aspx )
I'll do my best to answer though

> Following your README, if some field is not available - the value will be '_'.
> But in practice, those unavailable fields are just missing, skipping to the next field.
> 
> Do you plan to fix that issue?

Can you give me an example? I don't understand the issue

> התקשרו	התקשר	VB	VB	gen=F|gen=M|num=P|per=3|tense=PAST	8	relcomp	_	_
> 
> What is the meaning of the double appearance of 'gen' ?

I think this is for the case that either or both apply. I think both are indicated because in a syntactic frame morphological features like gender need to match between heads and dependents, and in Hebrew התקשרו can be feminine, masculine or both, while a head (or dependent) might be F, M, or both, in which case the only matches that don't work are F-M and M-F. This is as opposed to a morphological suffix that has a specific gender for example אכלתם vs אכלתן, where the former is empirically used when the inflection is for the plural of the masculine gender or a mixture of masculines and feminines, but the latter is typically used when the inflection of the plural is for only feminine or for a group consisting of mostly feminines.

In some formats like UD you would use gen=F,M but in this format we kept with the SPMRL way of doing things, which keeps them separate.

I suggest reaching out to Reut Tsarfaty or Yoav Goldberg for a better explanation.

**Comment by matanox** [comment]
@habeanf thanks a lot for this note! i think it should probably be prominently mentioned on the readme itself, about the deprecation by the newer repo, as i didn't realize it myself short of curiously going to the only open issue here to learn about that. the new repo in particular, has a superior getting started readme, and i guess this will also avoid some workloads arriving here (but what would i know).
